### PR TITLE
-ddmm.mmmm

### PR DESCRIPTION
**Pull request by hexameron**
dl-fldigi reported bad elevation and bearing for BONZO8.

### CODE REVIEW

**Comment by danielrichman** [comment]
Well, this is embarrassing. Thank you for the fix :-).

Could you---instead of replacing the ddmmmm test---have two tests? Maybe "test_ddmmmm" and "test_ddmmmm_negative".

Just copy the code, or refactor it out, or whatever, I don't feel very strongly about how it's done :-).

Cheers,
Daniel

**Comment by hexameron** [comment]
I can do that. There should be tests for -00mm.mmmm and -ddmm.mmmm, so duplicating the first test looks sensible.

**Comment by danielrichman** [comment]
https://github.com/danielrichman/dl-fldigi/commit/e937cc2240df0f1ab3203ba682c93ec51ba9683a

**Comment by danielrichman** [comment]
https://github.com/jamescoxon/dl-fldigi/pull/29

I will badger James

**Pull request merged**
